version: "3.9"
services:
  rust-server:
    build: 
      context: ./server # Use the current directory as the build context
      dockerfile: Dockerfile # Assuming your Dockerfile is named "Dockerfile"
    ports:
      - "3000:3000" # Map port 3000 on the host to the container
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb # Ensure MongoDB starts first

  mongodb:
    image: mongo:latest 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_root_user
      - MONGO_INITDB_ROOT_PASSWORD=your_root_password